dist: xenial
language: cpp
compiler: clang

install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user

addons:
  apt:
    packages:
    - libboost-test-dev
script:
# Download dependencies and build project
- conan install .
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uznseday:$BINTRAY_API_KEY "https://api.bintray.com/content/znseday/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
